name: Python Testing

on: [push]

jobs:
  csv-processor-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          exists() {
              [ -e "$1" ]
          }

          if exists requirements*.txt; then
            for f in requirements*.txt; do
              pip install -r $f;
            done
          fi
      - name: Test with pytest
        working-directory: ./backend
        run: |
          pytest
